#' Check numeric columns
#'
#' Internal function that checks whether a column contains positive numbers.
#'
#' @returns TRUE if values are all positive numeric and FALSE if not
#' @keywords internal
is_valid_numcol <- function(col_values) {
  is.numeric(col_values) & all(col_values >= 0) & all(!is.na(col_values))
}


#' Check numeric range columns
#'
#' This helper function checks whether a columns contains positive numbers between 0 and 1.
#'
#' @returns TRUE if values are all positive numeric between 0 and 1, FALSE if not
#' @keywords internal
is_valid_numrange <- function(col_values) {
  is.numeric(col_values) & all(col_values >= 0) & all(col_values <= 1) & all(!is.na(col_values))
}


#' Check dataframe
#'
#' Internal function that checks whether a dataframe is a dataframe or a tibble.
#'
#' @importFrom dplyr is_grouped_df
#' @keywords internal
is_valid_dataframe <- function(df) {
  is.data.frame(df) && (
    !is_grouped_df(df) && !inherits(df, "rowwise_df")
  )
}


#' Check for NA in dataframe columns
#'
#' Internal function that checks whether dataframe columns contain NAs.
#'
#' @importFrom purrr map_lgl
#' @keywords internal
check_na_cols <- function(df) {
  map_lgl(df, \(x) any(is.na(x)))
}


#' Validate model input
#'
#' Internal function that validates the structure of model input generated by
#' users.
#'
#' @importFrom purrr map_lgl
#' @keywords internal
validate_model_input <- function(model_input) {

  # Obtain required cols from data specification
  data_spec <- model_input_data_spec()
  required_cols <- names(data_spec)

  # Check for missing columns
  req_cols_present <- required_cols %in% names(model_input)
  if (!all(req_cols_present)) {
    stop(paste("the following columns are missing:", paste(required_cols[!req_cols_present], collapse = ", ")))
  }

  # Check whether column values are valid for required columns present in data
  col_vals_valid <- map_lgl(required_cols[req_cols_present], \(x) data_spec[[x]](model_input[[x]]))
  if (!all(col_vals_valid)) {
    stop(paste("the following columns contain invalid data:", paste(required_cols[!col_vals_valid], collapse = ", ")))
  }

}
